///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/music/prueba.aks
/// Generation time: dom nov  1 23:23:23 CET 2020
///

/// Song 'ambient_sound' metadata macros
#define ambient_sound_address  0x0041
#define ambient_sound_size     95
#define ambient_sound_end      0x9f

/// Song 'ambient_sound' array declaration
extern void ambient_sound[ambient_sound_size];
